import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle } from "@phosphor-icons/react";
import { Link, useOutletContext, useParams } from "react-router-dom";
import { getRabSubmissions } from "@/api";
import { actionRabSubmission } from "@/api";
import { actionRabRealization, completeRabRealization } from "@/api";
import { toast } from "sonner";
import AccessDenied from "@/components/AccessDenied";

export default function RabSubmissionDetailPage() {
  const { role } = useOutletContext();
  const { submissionId } = useParams();
  const [submission, setSubmission] = useState(null);
  const [notes, setNotes] = useState({});
  useEffect(() => { getRabSubmissions().then((items) => setSubmission(items.find((item) => item.id === submissionId))); }, [submissionId]);
  if (!["Koordinator", "SPV", "Manager", "Sekretaris Divisi", "PIC Accounting"].includes(role)) return <AccessDenied feature="Rincian RAB" roles="pengaju dan reviewer RAB" />;
  if (!submission) return <div className="page-message" data-testid="rab-detail-loading">Memuat rincian RAB...</div>;
  const canAct = (role === "Koordinator" && submission.status === "MENUNGGU KOORDINATOR") || (role === "SPV" && submission.status === "MENUNGGU SPV") || (role === "Manager" && submission.status === "MENUNGGU MANAGER") || (role === "Sekretaris Divisi" && submission.status === "MENUNGGU PEMESANAN");
  async function act(action) { try { const result = await actionRabSubmission(submission.id, { actor_role: role, action, component_notes: notes }); setSubmission(result); toast.success(action === "revisi" ? "RAB dikembalikan ke PIC." : "RAB diteruskan ke tahap berikutnya."); } catch (error) { toast.error(error.response?.data?.detail || "Tindakan belum dapat diproses."); } }
  async function completeRealization() { try { setSubmission(await completeRabRealization(submission.id)); toast.success("Realisasi selesai dikirim ke Sekretaris."); } catch (error) { toast.error("Nota tiap komponen belum lengkap."); } }
  async function reviewRealization(action) { try { setSubmission(await actionRabRealization(submission.id, { actor_role: role, action, component_notes: notes })); toast.success(action === "revisi" ? "Revisi lampiran dikirim ke PIC." : "BPH berhasil dibuat."); } catch (error) { toast.error("Review realisasi belum dapat diproses."); } }
  return <section className="page-content review-page" data-testid="rab-submission-detail-page"><Link className="text-button" to={role === "Sekretaris Divisi" ? "/inbox" : "/persetujuan"} data-testid="back-to-rab-list-link"><ArrowLeft size={17} /> Kembali ke antrean</Link><div className="page-heading"><div><p className="eyebrow">RINCIAN RAB / {submission.status}</p><h1>{submission.title}</h1><p>Rincian review PIC, bukti, dan catatan per komponen.</p></div></div><div className="review-bento">{submission.items.map((item, index) => <article key={`${item.label}-${index}`} className="proof-card" data-testid={`rab-detail-item-${index}`}><p className="eyebrow">{item.label}</p><strong>{item.title || item.mode}</strong><span>{item.time || item.date || item.distance}</span><p data-testid={`rab-detail-note-${index}`}>Notes PIC: {item.note || "—"}</p><img className="dummy-proof" src={item.proof_url} alt={`Bukti ${item.label}`} data-testid={`rab-detail-proof-${index}`} /><span><CheckCircle size={16} weight="fill" /> Bukti terlampir</span>{canAct && role !== "Sekretaris Divisi" && <label>Notes revisi (jika ada)<textarea value={notes[index] || ""} onChange={(event) => setNotes({ ...notes, [index]: event.target.value })} data-testid={`component-revision-note-${index}`} /></label>}</article>)}</div>{canAct && <div className="approval-actions" data-testid="rab-action-buttons">{role === "Sekretaris Divisi" ? <button className="primary-button" type="button" onClick={() => act("booked")} data-testid="mark-ticket-hotel-booked-button">Checklist tiket & hotel dipesan</button> : <><button className="secondary-button" type="button" onClick={() => act("revisi")} data-testid="revise-rab-button">Kirim revisi ke PIC</button><button className="primary-button" type="button" onClick={() => act("approve")} data-testid="approve-rab-button">Approve & teruskan</button></>}</div>}{role === "PIC Accounting" && submission.status === "SIAP REALISASI PIC" && <button className="primary-button" type="button" onClick={completeRealization} data-testid="send-realization-button">Kirim Realisasi ke Sekretaris</button>}{role === "Sekretaris Divisi" && submission.status === "SELESAI REALISASI" && <div className="approval-actions"><button className="secondary-button" type="button" onClick={() => reviewRealization("revisi")} data-testid="revise-realization-proof-button">Minta revisi lampiran</button><button className="primary-button" type="button" onClick={() => reviewRealization("bph_created")} data-testid="create-bph-button">Approve & buat BPH</button></div>}</section>;
}